### ISSUE TITLE
Does not handle url hash

### ISSUE THREAD

**Issue by rahatarmanahmed** [yoshuawuyts/url-querystring#2]
https://tonicdev.com/rahat/url-querystring-bad-hash

The hash gets included in the last parameter.

**Comment by yoshuawuyts** [comment]
Use Node's standard [url.parse](https://nodejs.org/api/url.html#url_url_parse_urlstr_parsequerystring_slashesdenotehost) instead:

``` js
const url = require('url')
url.parse(myUrl, true) // true signs to destructure the qs into an object
```
